import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToOne, JoinColumn } from 'typeorm';
import { Tenant } from '../../tenants/entities/tenant.entity';
import { Branch } from '../../branches/entities/branch.entity';

@Entity('devices')
export class Device {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @ManyToOne(() => Tenant, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'tenantId' })
    tenant: Tenant;

    @Column()
    tenantId: string;

    @ManyToOne(() => Branch, { onDelete: 'CASCADE', nullable: true })
    @JoinColumn({ name: 'branchId' })
    branch: Branch;

    @Column({ nullable: true })
    branchId: string;

    @Column()
    name: string;

    // A unique identifier generated by the client (e.g., stored in localStorage)
    @Column({ unique: true })
    identifier: string;

    @Column({ default: 'ACTIVE' }) // ACTIVE, REVOKED
    status: string;

    @Column({ type: 'timestamp', nullable: true })
    lastActive: Date;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
